# Derive bext dependency metadata from the existing build files.  This module
# deliberately does not introduce a manifest: CMakeLists.txt, per-project
# .deps files, wrapper install settings, .gitmodules, and the Git index remain
# the sources of truth.

function(_bext_inventory_key out value)
  string(TOUPPER "${value}" key)
  string(REGEX REPLACE "[^A-Z0-9]" "_" key "${key}")
  set(${out} "${key}" PARENT_SCOPE)
endfunction()

function(_bext_inventory_set project field value)
  _bext_inventory_key(key "${project}")
  set_property(GLOBAL PROPERTY "BEXT_INVENTORY_${key}_${field}" "${value}")
endfunction()

function(bext_inventory_get out project field)
  _bext_inventory_key(key "${project}")
  get_property(value GLOBAL PROPERTY "BEXT_INVENTORY_${key}_${field}")
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(_bext_inventory_submodule_lookup out_url out_sha source_dir path)
  get_property(entries GLOBAL PROPERTY BEXT_INVENTORY_SUBMODULES)
  foreach(entry ${entries})
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 entry_path)
    if ("${entry_path}" STREQUAL "${path}")
      list(GET parts 1 entry_url)
      execute_process(
        COMMAND git ls-tree HEAD -- "${path}"
        WORKING_DIRECTORY "${source_dir}"
        RESULT_VARIABLE tree_result
        OUTPUT_VARIABLE tree_line
        OUTPUT_STRIP_TRAILING_WHITESPACE
      )
      if (NOT tree_result EQUAL 0 OR NOT tree_line MATCHES "^[0-9]+ commit ([0-9a-f]+)")
        message(FATAL_ERROR "Unable to read pinned commit for submodule ${path}")
      endif()
      set(${out_url} "${entry_url}" PARENT_SCOPE)
      set(${out_sha} "${CMAKE_MATCH_1}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out_url} "" PARENT_SCOPE)
  set(${out_sha} "" PARENT_SCOPE)
endfunction()

function(bext_collect_dependency_inventory source_dir)
  get_filename_component(source_dir "${source_dir}" ABSOLUTE)
  if (NOT EXISTS "${source_dir}/CMakeLists.txt" OR NOT EXISTS "${source_dir}/.gitmodules")
    message(FATAL_ERROR "${source_dir} is not a bext source tree")
  endif()

  # Read submodule paths and URLs without requiring submodules to be populated.
  file(STRINGS "${source_dir}/.gitmodules" gitmodule_lines)
  set(submodules)
  set(current_path "")
  foreach(line ${gitmodule_lines})
    string(STRIP "${line}" line)
    if (line MATCHES "^path = (.+)$")
      set(current_path "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^url = (.+)$" AND current_path)
      list(APPEND submodules "${current_path}|${CMAKE_MATCH_1}")
      set(current_path "")
    endif()
  endforeach()
  set_property(GLOBAL PROPERTY BEXT_INVENTORY_SUBMODULES "${submodules}")

  file(STRINGS "${source_dir}/CMakeLists.txt" top_lines)
  set(projects)
  foreach(line ${top_lines})
    string(STRIP "${line}" stripped)
    if (stripped MATCHES "^#" OR NOT stripped MATCHES "^add_project\\(([^ )]+)")
      continue()
    endif()
    set(project "${CMAKE_MATCH_1}")
    list(APPEND projects "${project}")
    if (stripped MATCHES "GROUPS +\"([^\"]+)\"")
      set(groups "${CMAKE_MATCH_1}")
    else()
      set(groups "always considered")
    endif()
    _bext_inventory_set("${project}" GROUPS "${groups}")
  endforeach()
  list(REMOVE_DUPLICATES projects)

  set(all_providers)
  foreach(project ${projects})
    set(wrapper "${source_dir}/${project}/CMakeLists.txt")
    if (NOT EXISTS "${wrapper}")
      message(FATAL_ERROR "Project ${project} has no wrapper CMakeLists.txt")
    endif()
    file(READ "${wrapper}" wrapper_text)

    if (wrapper_text MATCHES "-DCMAKE_INSTALL_PREFIX=\\$\\{CMAKE_BUNDLE_INSTALL_PREFIX\\}" OR
        wrapper_text MATCHES "--prefix=\\$\\{CMAKE_BUNDLE_INSTALL_PREFIX\\}")
      set(output_class install)
    elseif(wrapper_text MATCHES "-DCMAKE_INSTALL_PREFIX=\\$\\{CMAKE_NOBUNDLE_INSTALL_PREFIX\\}" OR
           wrapper_text MATCHES "--prefix=\\$\\{CMAKE_NOBUNDLE_INSTALL_PREFIX\\}")
      set(output_class noinstall)
    elseif(wrapper_text MATCHES "CMAKE_BUNDLE_INSTALL_PREFIX" AND
           NOT wrapper_text MATCHES "CMAKE_NOBUNDLE_INSTALL_PREFIX")
      # Some custom build drivers (currently Tcl) receive the prefix through a
      # configured helper script rather than directly in ExternalProject_Add.
      set(output_class install)
    else()
      message(FATAL_ERROR "Cannot derive output class for ${project}")
    endif()
    _bext_inventory_set("${project}" OUTPUT "${output_class}")

    if (wrapper_text MATCHES "DOC_LICENSE_DIR")
      set(has_license TRUE)
    else()
      set(has_license FALSE)
    endif()
    _bext_inventory_set("${project}" HAS_LICENSE "${has_license}")

    set(deps)
    set(depfile "${source_dir}/${project}/${project}.deps")
    if (EXISTS "${depfile}")
      file(STRINGS "${depfile}" dep_lines)
      foreach(dep ${dep_lines})
        string(STRIP "${dep}" dep)
        if (dep AND NOT dep MATCHES "^#")
          string(TOLOWER "${dep}" dep)
          string(REPLACE "_" "-" dep "${dep}")
          list(APPEND deps "${dep}")
        endif()
      endforeach()
    endif()
    list(REMOVE_DUPLICATES deps)
    _bext_inventory_set("${project}" DEPS "${deps}")

    set(paths)
    string(REGEX MATCHALL "git_submodule_init\\([A-Za-z0-9_+./-]+ +" init_calls "${wrapper_text}")
    foreach(call ${init_calls})
      string(REGEX REPLACE "git_submodule_init\\(([A-Za-z0-9_+./-]+) +" "\\1" path "${call}")
      list(APPEND paths "${project}/${path}")
    endforeach()
    list(REMOVE_DUPLICATES paths)
    if (NOT paths)
      message(FATAL_ERROR "Project ${project} does not declare a source with git_submodule_init")
    endif()
    _bext_inventory_set("${project}" SUBMODULE_PATHS "${paths}")

    set(urls)
    set(shas)
    foreach(path ${paths})
      _bext_inventory_submodule_lookup(url sha "${source_dir}" "${path}")
      if (NOT url)
        message(FATAL_ERROR "${project} uses ${path}, but it is absent from .gitmodules")
      endif()
      list(APPEND urls "${url}")
      list(APPEND shas "${sha}")
    endforeach()
    _bext_inventory_set("${project}" SOURCE_URLS "${urls}")
    _bext_inventory_set("${project}" SOURCE_SHAS "${shas}")

    string(REGEX MATCHALL "ExternalProject_Add\\([A-Za-z0-9_+-]+_BLD" provider_calls "${wrapper_text}")
    foreach(call ${provider_calls})
      string(REGEX REPLACE "ExternalProject_Add\\(([A-Za-z0-9_+-]+)_BLD" "\\1" provider "${call}")
      string(TOLOWER "${provider}" provider)
      string(REPLACE "_" "-" provider "${provider}")
      list(APPEND all_providers "${provider}")
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES all_providers)

  # Validate dependency references and topological consistency.
  foreach(project ${projects})
    bext_inventory_get(deps "${project}" DEPS)
    foreach(dep ${deps})
      list(FIND projects "${dep}" project_index)
      list(FIND all_providers "${dep}" provider_index)
      if (project_index EQUAL -1 AND provider_index EQUAL -1)
        message(FATAL_ERROR "${project}.deps references unknown dependency ${dep}")
      endif()
    endforeach()
  endforeach()

  set(resolved)
  set(remaining ${projects})
  while(remaining)
    set(progress FALSE)
    foreach(project ${remaining})
      bext_inventory_get(deps "${project}" DEPS)
      set(ready TRUE)
      foreach(dep ${deps})
        list(FIND projects "${dep}" dep_project_index)
        if (NOT dep_project_index EQUAL -1)
          list(FIND resolved "${dep}" resolved_index)
          if (resolved_index EQUAL -1)
            set(ready FALSE)
          endif()
        endif()
      endforeach()
      if (ready)
        list(APPEND resolved "${project}")
        list(REMOVE_ITEM remaining "${project}")
        set(progress TRUE)
      endif()
    endforeach()
    if (NOT progress)
      message(FATAL_ERROR "Dependency cycle detected among: ${remaining}")
    endif()
  endwhile()

  # Distributed outputs must install their legal notice alongside the bundle.
  foreach(project ${projects})
    bext_inventory_get(output_class "${project}" OUTPUT)
    bext_inventory_get(has_license "${project}" HAS_LICENSE)
    if (output_class STREQUAL "install" AND NOT has_license)
      message(FATAL_ERROR "Bundled project ${project} does not install a license via DOC_LICENSE_DIR")
    endif()
  endforeach()

  list(SORT projects)
  set(BEXT_INVENTORY_PROJECTS "${projects}" PARENT_SCOPE)
endfunction()
