if (NOT DEFINED BEXT_SOURCE_DIR)
  message(FATAL_ERROR "BEXT_SOURCE_DIR is required")
endif()
if (NOT DEFINED BEXT_SBOM_OUTPUT)
  message(FATAL_ERROR "BEXT_SBOM_OUTPUT is required")
endif()

include("${BEXT_SOURCE_DIR}/CMake/BextDependencyInventory.cmake")
bext_collect_dependency_inventory("${BEXT_SOURCE_DIR}")

function(_bext_json_escape out value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(_bext_spdx_id out project)
  string(REGEX REPLACE "[^A-Za-z0-9.-]" "-" id "${project}")
  set(${out} "SPDXRef-Package-${id}" PARENT_SCOPE)
endfunction()

execute_process(
  COMMAND git rev-parse HEAD
  WORKING_DIRECTORY "${BEXT_SOURCE_DIR}"
  RESULT_VARIABLE git_result
  OUTPUT_VARIABLE bext_revision
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
if (NOT git_result EQUAL 0)
  message(FATAL_ERROR "Unable to determine the bext revision")
endif()
string(TIMESTAMP created "%Y-%m-%dT%H:%M:%SZ" UTC)

get_filename_component(sbom_dir "${BEXT_SBOM_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${sbom_dir}")
file(WRITE "${BEXT_SBOM_OUTPUT}" "{\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"spdxVersion\": \"SPDX-2.3\",\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"dataLicense\": \"CC0-1.0\",\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"SPDXID\": \"SPDXRef-DOCUMENT\",\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"name\": \"bext-dependencies\",\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"documentNamespace\": \"https://github.com/BRL-CAD/bext/sbom/${bext_revision}\",\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"creationInfo\": {\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "    \"created\": \"${created}\",\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "    \"creators\": [\"Tool: bext-GenerateSbom.cmake\"]\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  },\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"packages\": [\n")

list(LENGTH BEXT_INVENTORY_PROJECTS project_count)
set(project_index 0)
foreach(project ${BEXT_INVENTORY_PROJECTS})
  math(EXPR project_index "${project_index} + 1")
  bext_inventory_get(groups "${project}" GROUPS)
  bext_inventory_get(output_class "${project}" OUTPUT)
  bext_inventory_get(urls "${project}" SOURCE_URLS)
  bext_inventory_get(shas "${project}" SOURCE_SHAS)
  list(GET urls 0 primary_url)
  list(GET shas 0 primary_sha)
  _bext_spdx_id(spdx_id "${project}")
  string(REPLACE ";" ", " all_urls "${urls}")
  string(REPLACE ";" ", " all_shas "${shas}")
  string(REPLACE ";" ", " group_text "${groups}")
  _bext_json_escape(comment "groups: ${group_text}; output: ${output_class}; sources: ${all_urls}; pinned commits: ${all_shas}")
  _bext_json_escape(primary_url "${primary_url}")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "    {\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"name\": \"${project}\",\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"SPDXID\": \"${spdx_id}\",\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"versionInfo\": \"${primary_sha}\",\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"downloadLocation\": \"${primary_url}\",\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"filesAnalyzed\": false,\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"licenseConcluded\": \"NOASSERTION\",\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"licenseDeclared\": \"NOASSERTION\",\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"copyrightText\": \"NOASSERTION\",\n")
  file(APPEND "${BEXT_SBOM_OUTPUT}" "      \"comment\": \"${comment}\"\n")
  if (project_index LESS project_count)
    file(APPEND "${BEXT_SBOM_OUTPUT}" "    },\n")
  else()
    file(APPEND "${BEXT_SBOM_OUTPUT}" "    }\n")
  endif()
endforeach()
file(APPEND "${BEXT_SBOM_OUTPUT}" "  ],\n")
file(APPEND "${BEXT_SBOM_OUTPUT}" "  \"relationships\": [\n")

set(relationships)
foreach(project ${BEXT_INVENTORY_PROJECTS})
  _bext_spdx_id(project_id "${project}")
  list(APPEND relationships "SPDXRef-DOCUMENT|DESCRIBES|${project_id}")
  bext_inventory_get(deps "${project}" DEPS)
  foreach(dep ${deps})
    list(FIND BEXT_INVENTORY_PROJECTS "${dep}" dep_index)
    if (NOT dep_index EQUAL -1)
      _bext_spdx_id(dep_id "${dep}")
      list(APPEND relationships "${project_id}|DEPENDS_ON|${dep_id}")
    endif()
  endforeach()
endforeach()
list(LENGTH relationships relationship_count)
set(relationship_index 0)
foreach(relationship ${relationships})
  math(EXPR relationship_index "${relationship_index} + 1")
  string(REPLACE "|" ";" parts "${relationship}")
  list(GET parts 0 source_id)
  list(GET parts 1 relationship_type)
  list(GET parts 2 target_id)
  file(APPEND "${BEXT_SBOM_OUTPUT}" "    {\"spdxElementId\": \"${source_id}\", \"relationshipType\": \"${relationship_type}\", \"relatedSpdxElement\": \"${target_id}\"}")
  if (relationship_index LESS relationship_count)
    file(APPEND "${BEXT_SBOM_OUTPUT}" ",\n")
  else()
    file(APPEND "${BEXT_SBOM_OUTPUT}" "\n")
  endif()
endforeach()
file(APPEND "${BEXT_SBOM_OUTPUT}" "  ]\n}\n")
message(STATUS "Generated SPDX 2.3 SBOM: ${BEXT_SBOM_OUTPUT}")
