if (NOT DEFINED BEXT_SOURCE_DIR)
  message(FATAL_ERROR "BEXT_SOURCE_DIR is required")
endif ()

if (NOT DEFINED BEXT_BINARY_DIR)
  message(FATAL_ERROR "BEXT_BINARY_DIR is required")
endif ()

set(graph_dot "${BEXT_BINARY_DIR}/bext.dot")
set(graph_svg "${BEXT_BINARY_DIR}/bext.svg")

function(_bext_graph_normalize_id out raw_value)
  string(TOLOWER "${raw_value}" normalized)
  string(REPLACE "_" "-" normalized "${normalized}")
  set(${out} "${normalized}" PARENT_SCOPE)
endfunction()

function(_bext_graph_key out raw_value)
  string(REGEX REPLACE "[^A-Za-z0-9]" "_" key "${raw_value}")
  set(${out} "${key}" PARENT_SCOPE)
endfunction()

function(_bext_graph_set prefix node_id value)
  _bext_graph_key(prop_key "${node_id}")
  set_property(GLOBAL PROPERTY "${prefix}_${prop_key}" "${value}")
endfunction()

function(_bext_graph_get out prefix node_id)
  _bext_graph_key(prop_key "${node_id}")
  get_property(prop_value GLOBAL PROPERTY "${prefix}_${prop_key}")
  set(${out} "${prop_value}" PARENT_SCOPE)
endfunction()

function(_bext_graph_append prefix node_id value)
  _bext_graph_key(prop_key "${node_id}")
  get_property(prop_values GLOBAL PROPERTY "${prefix}_${prop_key}")
  list(APPEND prop_values "${value}")
  list(REMOVE_DUPLICATES prop_values)
  set_property(GLOBAL PROPERTY "${prefix}_${prop_key}" "${prop_values}")
endfunction()

function(_bext_graph_get_list out prefix node_id)
  _bext_graph_key(prop_key "${node_id}")
  get_property(prop_values GLOBAL PROPERTY "${prefix}_${prop_key}")
  set(${out} "${prop_values}" PARENT_SCOPE)
endfunction()

function(_bext_graph_quote out value)
  string(REPLACE "\"" "\\\"" escaped "${value}")
  set(${out} "\"${escaped}\"" PARENT_SCOPE)
endfunction()

function(_bext_graph_label out value)
  string(REPLACE "-" " " label_text "${value}")
  set(${out} "${label_text}" PARENT_SCOPE)
endfunction()

function(_bext_graph_xml_escape out value)
  string(REPLACE "&" "&amp;" escaped "${value}")
  string(REPLACE "<" "&lt;" escaped "${escaped}")
  string(REPLACE ">" "&gt;" escaped "${escaped}")
  string(REPLACE "\"" "&quot;" escaped "${escaped}")
  set(${out} "${escaped}" PARENT_SCOPE)
endfunction()

function(_bext_graph_write_line)
  cmake_parse_arguments(ARG "" "TEXT" "" ${ARGN})
  file(APPEND "${graph_dot}" "${ARG_TEXT}\n")
endfunction()

function(_bext_graph_color_by_depth out_fill out_outline out_font out_outline_font depth output_class)
  set(strong_colors "#2563eb" "#0f766e" "#65a30d" "#d97706" "#dc2626" "#9333ea" "#0891b2" "#4f46e5")
  set(pale_colors "#dbeafe" "#ccfbf1" "#ecfccb" "#ffedd5" "#fee2e2" "#f3e8ff" "#cffafe" "#e0e7ff")
  set(strong_fonts "#ffffff" "#ffffff" "#111827" "#111827" "#ffffff" "#ffffff" "#111827" "#ffffff")
  math(EXPR palette_index "(${depth} - 1) % 8")
  list(GET strong_colors ${palette_index} strong_fill)
  list(GET pale_colors ${palette_index} pale_fill)
  list(GET strong_fonts ${palette_index} strong_font)
  if ("${output_class}" STREQUAL "noinstall")
    set(${out_fill} "${pale_fill}" PARENT_SCOPE)
    set(${out_outline} "${strong_fill}" PARENT_SCOPE)
    set(${out_font} "${strong_fill}" PARENT_SCOPE)
    set(${out_outline_font} "${strong_fill}" PARENT_SCOPE)
  else ()
    set(${out_fill} "${strong_fill}" PARENT_SCOPE)
    set(${out_outline} "${strong_fill}" PARENT_SCOPE)
    set(${out_font} "${strong_font}" PARENT_SCOPE)
    set(${out_outline_font} "${strong_fill}" PARENT_SCOPE)
  endif ()
endfunction()

function(_bext_graph_find_submodule_url out project_name submodule_path)
  set(search_path "${project_name}/${submodule_path}")
  list(LENGTH submodule_path_entries submodule_count)
  if (submodule_count GREATER 0)
    math(EXPR last_index "${submodule_count} - 1")
    foreach(idx RANGE 0 ${last_index})
      list(GET submodule_path_entries ${idx} entry)
      string(REPLACE "|" ";" parts "${entry}")
      list(GET parts 0 entry_path)
      list(GET parts 1 entry_url)
      if ("${entry_path}" STREQUAL "${search_path}")
        set(${out} "${entry_url}" PARENT_SCOPE)
        return()
      endif ()
    endforeach ()
  endif ()
  set(${out} "" PARENT_SCOPE)
endfunction()

file(STRINGS "${BEXT_SOURCE_DIR}/.gitmodules" gitmodule_lines)
set(current_submodule_path "")
foreach(line ${gitmodule_lines})
  string(STRIP "${line}" stripped_line)
  if (stripped_line MATCHES "^path = (.+)$")
    set(current_submodule_path "${CMAKE_MATCH_1}")
  endif ()
  if (stripped_line MATCHES "^url = (.+)$")
    if (current_submodule_path)
      list(APPEND submodule_path_entries "${current_submodule_path}|${CMAKE_MATCH_1}")
      set(current_submodule_path "")
    endif ()
  endif ()
endforeach()

file(STRINGS "${BEXT_SOURCE_DIR}/CMakeLists.txt" top_level_lines)

set(project_ids)
set(actual_edges)
set(all_dep_ids)
foreach(line ${top_level_lines})
  string(STRIP "${line}" stripped_line)
  if (stripped_line MATCHES "^#")
    continue()
  endif ()
  if (NOT stripped_line MATCHES "^add_project\\(([^ \t\\)]+)")
    continue()
  endif ()

  set(project_name "${CMAKE_MATCH_1}")
  _bext_graph_normalize_id(project_id "${project_name}")
  list(APPEND project_ids "${project_id}")
  _bext_graph_set(NODE_LABEL "${project_id}" "${project_name}")
  _bext_graph_set(NODE_CLASS "${project_id}" "install")

  set(project_cmakelists "${BEXT_SOURCE_DIR}/${project_name}/CMakeLists.txt")
  file(READ "${project_cmakelists}" project_text)
  if (project_text MATCHES "CMAKE_INSTALL_PREFIX=\\$\\{CMAKE_NOBUNDLE_INSTALL_PREFIX\\}" OR
      project_text MATCHES "--prefix=\\$\\{CMAKE_NOBUNDLE_INSTALL_PREFIX\\}")
    _bext_graph_set(NODE_CLASS "${project_id}" "noinstall")
  endif ()

  set(depfile "${BEXT_SOURCE_DIR}/${project_name}/${project_name}.deps")
  if (EXISTS "${depfile}")
    file(STRINGS "${depfile}" dep_lines)
    foreach(dep_line ${dep_lines})
      string(STRIP "${dep_line}" dep_name)
      if (NOT dep_name)
        continue()
      endif ()
      _bext_graph_normalize_id(dep_id "${dep_name}")
      list(APPEND actual_edges "${project_id}|${dep_id}")
      list(APPEND all_dep_ids "${dep_id}")
      _bext_graph_get(dep_label NODE_LABEL "${dep_id}")
      if (NOT dep_label)
        string(TOLOWER "${dep_name}" dep_label_text)
        _bext_graph_set(NODE_LABEL "${dep_id}" "${dep_label_text}")
      endif ()
    endforeach ()
  endif ()

  file(STRINGS "${project_cmakelists}" project_lines)
  foreach(project_line ${project_lines})
    string(STRIP "${project_line}" stripped_project_line)
    if (stripped_project_line MATCHES "git_submodule_init\\(([A-Za-z0-9_+./-]+)[ \t]")
      list(APPEND submodule_paths "${CMAKE_MATCH_1}")
    endif ()
    if (stripped_project_line MATCHES "ExternalProject_Add\\(([A-Za-z0-9_]+)_BLD")
      _bext_graph_normalize_id(provider_id "${CMAKE_MATCH_1}")
      list(APPEND provider_ids "${provider_id}")
    endif ()
  endforeach ()
  list(REMOVE_DUPLICATES submodule_paths)
  list(REMOVE_DUPLICATES provider_ids)
  if (submodule_paths)
    _bext_graph_set(PROJECT_SUBMODULE_PATHS "${project_id}" "${submodule_paths}")
  endif ()
  if (provider_ids)
    _bext_graph_set(PROJECT_PROVIDER_IDS "${project_id}" "${provider_ids}")
  endif ()
  unset(submodule_paths)
  unset(provider_ids)
endforeach()

list(REMOVE_DUPLICATES project_ids)
list(SORT project_ids)
list(REMOVE_DUPLICATES actual_edges)
list(REMOVE_DUPLICATES all_dep_ids)

set(alias_ids)
foreach(dep_id ${all_dep_ids})
  list(FIND project_ids "${dep_id}" project_idx)
  if (project_idx EQUAL -1)
    list(APPEND alias_ids "${dep_id}")
  endif ()
endforeach()
list(REMOVE_DUPLICATES alias_ids)
list(SORT alias_ids)

set(provider_edges)
foreach(project_id ${project_ids})
  _bext_graph_get(project_name NODE_LABEL "${project_id}")
  _bext_graph_get(project_submodule_paths PROJECT_SUBMODULE_PATHS "${project_id}")
  foreach(submodule_path ${project_submodule_paths})
    _bext_graph_find_submodule_url(project_url "${project_name}" "${submodule_path}")
    if (project_url)
      _bext_graph_set(NODE_URL "${project_id}" "${project_url}")
      break()
    endif ()
  endforeach ()

  _bext_graph_get(provider_ids PROJECT_PROVIDER_IDS "${project_id}")
  foreach(provider_id ${provider_ids})
    list(FIND alias_ids "${provider_id}" alias_idx)
    if (alias_idx EQUAL -1)
      continue()
    endif ()
    list(APPEND provider_edges "${project_id}|${provider_id}")
    _bext_graph_get(alias_url NODE_URL "${provider_id}")
    if (NOT alias_url)
      foreach(submodule_path ${project_submodule_paths})
        get_filename_component(submodule_name "${submodule_path}" NAME)
        _bext_graph_normalize_id(submodule_id "${submodule_name}")
        if ("${submodule_id}" STREQUAL "${provider_id}")
          _bext_graph_find_submodule_url(alias_url_candidate "${project_name}" "${submodule_path}")
          if (alias_url_candidate)
            _bext_graph_set(NODE_URL "${provider_id}" "${alias_url_candidate}")
            break()
          endif ()
        endif ()
      endforeach ()
    endif ()
    _bext_graph_get(alias_class NODE_CLASS "${provider_id}")
    if (NOT alias_class)
      _bext_graph_get(project_class NODE_CLASS "${project_id}")
      _bext_graph_set(NODE_CLASS "${provider_id}" "${project_class}")
    endif ()
  endforeach ()
endforeach()
list(REMOVE_DUPLICATES provider_edges)
list(SORT provider_edges)

set(node_ids ${project_ids} ${alias_ids})
list(REMOVE_DUPLICATES node_ids)
list(SORT node_ids)

set(incoming_project_targets)
foreach(edge ${actual_edges})
  string(REPLACE "|" ";" edge_parts "${edge}")
  list(GET edge_parts 0 edge_src)
  list(GET edge_parts 1 edge_dst)
  list(FIND project_ids "${edge_dst}" dst_project_idx)
  if (NOT dst_project_idx EQUAL -1)
    list(APPEND incoming_project_targets "${edge_dst}")
  endif ()
endforeach()
list(REMOVE_DUPLICATES incoming_project_targets)

set(entry_project_ids)
foreach(project_id ${project_ids})
  list(FIND incoming_project_targets "${project_id}" incoming_idx)
  if (incoming_idx EQUAL -1)
    list(APPEND entry_project_ids "${project_id}")
  endif ()
endforeach()
list(SORT entry_project_ids)

set(active_nodes ${entry_project_ids})
foreach(project_id ${entry_project_ids})
  _bext_graph_set(NODE_DEPTH "${project_id}" "1")
endforeach()

set(changed TRUE)
while (changed)
  set(changed FALSE)
  foreach(edge ${actual_edges})
    string(REPLACE "|" ";" edge_parts "${edge}")
    list(GET edge_parts 0 edge_src)
    list(GET edge_parts 1 edge_dst)
    _bext_graph_get(src_depth NODE_DEPTH "${edge_src}")
    if (NOT src_depth)
      continue()
    endif ()
    math(EXPR candidate_depth "${src_depth} + 1")
    _bext_graph_get(dst_depth NODE_DEPTH "${edge_dst}")
    if (NOT dst_depth OR candidate_depth LESS dst_depth)
      _bext_graph_set(NODE_DEPTH "${edge_dst}" "${candidate_depth}")
      set(changed TRUE)
    endif ()
  endforeach ()
endwhile ()

foreach(node_id ${node_ids})
  _bext_graph_get(node_depth NODE_DEPTH "${node_id}")
  if (NOT node_depth)
    _bext_graph_set(NODE_DEPTH "${node_id}" "1")
  endif ()
endforeach()

set(max_depth 1)
foreach(node_id ${node_ids})
  _bext_graph_get(node_depth NODE_DEPTH "${node_id}")
  if (node_depth GREATER max_depth)
    set(max_depth "${node_depth}")
  endif ()
endforeach()

file(WRITE "${graph_dot}" "digraph Deps {\n")
_bext_graph_write_line(TEXT "  graph [rankdir=LR, overlap=false, splines=true];")
_bext_graph_write_line(TEXT "  node [shape=box, style=bold, fontname=\"Helvetica\", penwidth=2.0, margin=\"0.12,0.06\"];")
_bext_graph_write_line(TEXT "  edge [color=\"#6b7280\", arrowsize=0.7, penwidth=1.4];")
_bext_graph_write_line(TEXT "")

_bext_graph_write_line(TEXT "  \"BRL_CAD\" [label=\"BRL-CAD\", URL=\"https://github.com/BRL-CAD/brlcad\", style=\"filled,bold\", fillcolor=\"#111827\", color=\"#111827\", fontcolor=\"#ffffff\", penwidth=2.4];")
_bext_graph_write_line(TEXT "")

foreach(depth RANGE 1 ${max_depth})
  set(depth_nodes)
  foreach(node_id ${node_ids})
    _bext_graph_get(node_depth NODE_DEPTH "${node_id}")
    if ("${node_depth}" STREQUAL "${depth}")
      list(APPEND depth_nodes "${node_id}")
    endif ()
  endforeach ()
  if (depth_nodes)
    list(SORT depth_nodes)
    _bext_graph_write_line(TEXT "  { rank=same;")
    foreach(node_id ${depth_nodes})
      _bext_graph_get(node_label NODE_LABEL "${node_id}")
      _bext_graph_get(node_class NODE_CLASS "${node_id}")
      _bext_graph_get(node_url NODE_URL "${node_id}")
      _bext_graph_color_by_depth(node_fill node_outline node_font node_outline_font "${depth}" "${node_class}")
      _bext_graph_quote(node_name_q "${node_id}")
      _bext_graph_quote(node_label_q "${node_label}")
      if (node_url)
        _bext_graph_quote(node_url_q "${node_url}")
        set(url_attr ", URL=${node_url_q}")
      else ()
        set(url_attr "")
      endif ()
      if ("${node_class}" STREQUAL "noinstall")
        set(node_style "filled,bold")
      else ()
        set(node_style "filled,bold")
      endif ()
      _bext_graph_write_line(TEXT "    ${node_name_q} [label=${node_label_q}, style=\"${node_style}\", fillcolor=\"${node_fill}\", color=\"${node_outline}\", fontcolor=\"${node_font}\"${url_attr}];")
    endforeach ()
    _bext_graph_write_line(TEXT "  }")
    _bext_graph_write_line(TEXT "")
  endif ()
endforeach ()

foreach(entry_project_id ${entry_project_ids})
  _bext_graph_quote(entry_q "${entry_project_id}")
  _bext_graph_write_line(TEXT "  \"BRL_CAD\" -> ${entry_q} [color=\"#9ca3af\", penwidth=1.6];")
endforeach ()
if (entry_project_ids)
  _bext_graph_write_line(TEXT "")
endif ()

list(SORT actual_edges)
foreach(edge ${actual_edges})
  string(REPLACE "|" ";" edge_parts "${edge}")
  list(GET edge_parts 0 edge_src)
  list(GET edge_parts 1 edge_dst)
  _bext_graph_quote(src_q "${edge_src}")
  _bext_graph_quote(dst_q "${edge_dst}")
  _bext_graph_write_line(TEXT "  ${src_q} -> ${dst_q};")
endforeach ()

if (provider_edges)
  _bext_graph_write_line(TEXT "")
  foreach(edge ${provider_edges})
    string(REPLACE "|" ";" edge_parts "${edge}")
    list(GET edge_parts 0 edge_src)
    list(GET edge_parts 1 edge_dst)
    _bext_graph_quote(src_q "${edge_src}")
    _bext_graph_quote(dst_q "${edge_dst}")
    _bext_graph_write_line(TEXT "  ${src_q} -> ${dst_q} [style=dashed, color=\"#9ca3af\", arrowhead=none, constraint=false];")
  endforeach ()
endif ()

_bext_graph_write_line(TEXT "}")

set(node_width 190)
set(node_height 42)
set(column_gap 120)
set(row_gap 22)
set(graph_margin 40)

set(max_nodes_per_depth 1)
foreach(depth RANGE 1 ${max_depth})
  set(depth_nodes)
  foreach(node_id ${node_ids})
    _bext_graph_get(node_depth NODE_DEPTH "${node_id}")
    if ("${node_depth}" STREQUAL "${depth}")
      list(APPEND depth_nodes "${node_id}")
    endif ()
  endforeach ()
  list(LENGTH depth_nodes depth_node_count)
  if (depth_node_count GREATER max_nodes_per_depth)
    set(max_nodes_per_depth "${depth_node_count}")
  endif ()
endforeach ()

math(EXPR graph_width "${graph_margin} * 2 + (${max_depth} + 1) * ${node_width} + ${max_depth} * ${column_gap}")
math(EXPR graph_height "${graph_margin} * 2 + ${max_nodes_per_depth} * ${node_height} + (${max_nodes_per_depth} - 1) * ${row_gap}")
math(EXPR root_x "${graph_margin}")
math(EXPR root_y "(${graph_height} - ${node_height}) / 2")

foreach(node_id ${node_ids})
  _bext_graph_get(node_depth NODE_DEPTH "${node_id}")
  set(depth_nodes)
  foreach(depth_node_id ${node_ids})
    _bext_graph_get(depth_node_depth NODE_DEPTH "${depth_node_id}")
    if ("${depth_node_depth}" STREQUAL "${node_depth}")
      list(APPEND depth_nodes "${depth_node_id}")
    endif ()
  endforeach ()
  list(SORT depth_nodes)
  list(FIND depth_nodes "${node_id}" depth_index)
  math(EXPR node_x "${graph_margin} + ${node_depth} * (${node_width} + ${column_gap})")
  math(EXPR node_y "${graph_margin} + ${depth_index} * (${node_height} + ${row_gap})")
  _bext_graph_set(NODE_X "${node_id}" "${node_x}")
  _bext_graph_set(NODE_Y "${node_id}" "${node_y}")
endforeach ()

file(WRITE "${graph_svg}" "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"${graph_width}\" height=\"${graph_height}\" viewBox=\"0 0 ${graph_width} ${graph_height}\">\n")
file(APPEND "${graph_svg}" "  <defs>\n")
file(APPEND "${graph_svg}" "    <marker id=\"arrow\" markerWidth=\"10\" markerHeight=\"8\" refX=\"9\" refY=\"4\" orient=\"auto\" markerUnits=\"strokeWidth\">\n")
file(APPEND "${graph_svg}" "      <path d=\"M0,0 L10,4 L0,8 z\" fill=\"#6b7280\" />\n")
file(APPEND "${graph_svg}" "    </marker>\n")
file(APPEND "${graph_svg}" "  </defs>\n")
file(APPEND "${graph_svg}" "  <rect width=\"100%\" height=\"100%\" fill=\"#ffffff\" />\n")

foreach(entry_project_id ${entry_project_ids})
  _bext_graph_get(dst_x NODE_X "${entry_project_id}")
  _bext_graph_get(dst_y NODE_Y "${entry_project_id}")
  math(EXPR src_cx "${root_x} + ${node_width}")
  math(EXPR src_cy "${root_y} + (${node_height} / 2)")
  set(dst_cx "${dst_x}")
  math(EXPR dst_cy "${dst_y} + (${node_height} / 2)")
  math(EXPR control_dx "(${dst_cx} - ${src_cx}) / 2")
  math(EXPR control1_x "${src_cx} + ${control_dx}")
  math(EXPR control2_x "${dst_cx} - ${control_dx}")
  file(APPEND "${graph_svg}" "  <path d=\"M ${src_cx} ${src_cy} C ${control1_x} ${src_cy}, ${control2_x} ${dst_cy}, ${dst_cx} ${dst_cy}\" fill=\"none\" stroke=\"#9ca3af\" stroke-width=\"1.6\" marker-end=\"url(#arrow)\" />\n")
endforeach ()

foreach(edge ${actual_edges})
  string(REPLACE "|" ";" edge_parts "${edge}")
  list(GET edge_parts 0 edge_src)
  list(GET edge_parts 1 edge_dst)
  _bext_graph_get(src_x NODE_X "${edge_src}")
  _bext_graph_get(src_y NODE_Y "${edge_src}")
  _bext_graph_get(dst_x NODE_X "${edge_dst}")
  _bext_graph_get(dst_y NODE_Y "${edge_dst}")
  math(EXPR src_cx "${src_x} + ${node_width}")
  math(EXPR src_cy "${src_y} + (${node_height} / 2)")
  set(dst_cx "${dst_x}")
  math(EXPR dst_cy "${dst_y} + (${node_height} / 2)")
  math(EXPR control_dx "(${dst_cx} - ${src_cx}) / 2")
  math(EXPR control1_x "${src_cx} + ${control_dx}")
  math(EXPR control2_x "${dst_cx} - ${control_dx}")
  file(APPEND "${graph_svg}" "  <path d=\"M ${src_cx} ${src_cy} C ${control1_x} ${src_cy}, ${control2_x} ${dst_cy}, ${dst_cx} ${dst_cy}\" fill=\"none\" stroke=\"#6b7280\" stroke-width=\"1.4\" marker-end=\"url(#arrow)\" />\n")
endforeach ()

foreach(edge ${provider_edges})
  string(REPLACE "|" ";" edge_parts "${edge}")
  list(GET edge_parts 0 edge_src)
  list(GET edge_parts 1 edge_dst)
  _bext_graph_get(src_x NODE_X "${edge_src}")
  _bext_graph_get(src_y NODE_Y "${edge_src}")
  _bext_graph_get(dst_x NODE_X "${edge_dst}")
  _bext_graph_get(dst_y NODE_Y "${edge_dst}")
  math(EXPR src_cx "${src_x} + ${node_width}")
  math(EXPR src_cy "${src_y} + (${node_height} / 2)")
  set(dst_cx "${dst_x}")
  math(EXPR dst_cy "${dst_y} + (${node_height} / 2)")
  math(EXPR control_dx "(${dst_cx} - ${src_cx}) / 2")
  math(EXPR control1_x "${src_cx} + ${control_dx}")
  math(EXPR control2_x "${dst_cx} - ${control_dx}")
  file(APPEND "${graph_svg}" "  <path d=\"M ${src_cx} ${src_cy} C ${control1_x} ${src_cy}, ${control2_x} ${dst_cy}, ${dst_cx} ${dst_cy}\" fill=\"none\" stroke=\"#9ca3af\" stroke-width=\"1.4\" stroke-dasharray=\"6 5\" />\n")
endforeach ()

file(APPEND "${graph_svg}" "  <g>\n")
file(APPEND "${graph_svg}" "    <a xlink:href=\"https://github.com/BRL-CAD/brlcad\">\n")
file(APPEND "${graph_svg}" "      <rect x=\"${root_x}\" y=\"${root_y}\" width=\"${node_width}\" height=\"${node_height}\" rx=\"8\" fill=\"#111827\" stroke=\"#111827\" stroke-width=\"2.4\" />\n")
math(EXPR root_text_x "${root_x} + (${node_width} / 2)")
math(EXPR root_text_y "${root_y} + 27")
file(APPEND "${graph_svg}" "      <text x=\"${root_text_x}\" y=\"${root_text_y}\" text-anchor=\"middle\" font-family=\"Helvetica\" font-size=\"16\" font-weight=\"700\" fill=\"#ffffff\">BRL-CAD</text>\n")
file(APPEND "${graph_svg}" "    </a>\n")
file(APPEND "${graph_svg}" "  </g>\n")

foreach(node_id ${node_ids})
  _bext_graph_get(node_depth NODE_DEPTH "${node_id}")
  _bext_graph_get(node_label NODE_LABEL "${node_id}")
  _bext_graph_get(node_class NODE_CLASS "${node_id}")
  _bext_graph_get(node_url NODE_URL "${node_id}")
  _bext_graph_get(node_x NODE_X "${node_id}")
  _bext_graph_get(node_y NODE_Y "${node_id}")
  _bext_graph_color_by_depth(node_fill node_outline node_font node_outline_font "${node_depth}" "${node_class}")
  _bext_graph_xml_escape(node_label_xml "${node_label}")
  if (node_url)
    _bext_graph_xml_escape(node_url_xml "${node_url}")
    file(APPEND "${graph_svg}" "  <g>\n")
    file(APPEND "${graph_svg}" "    <a xlink:href=\"${node_url_xml}\">\n")
  else ()
    file(APPEND "${graph_svg}" "  <g>\n")
  endif ()
  file(APPEND "${graph_svg}" "      <rect x=\"${node_x}\" y=\"${node_y}\" width=\"${node_width}\" height=\"${node_height}\" rx=\"8\" fill=\"${node_fill}\" stroke=\"${node_outline}\" stroke-width=\"2.0\" />\n")
  math(EXPR text_x "${node_x} + (${node_width} / 2)")
  math(EXPR text_y "${node_y} + 27")
  file(APPEND "${graph_svg}" "      <text x=\"${text_x}\" y=\"${text_y}\" text-anchor=\"middle\" font-family=\"Helvetica\" font-size=\"14\" font-weight=\"600\" fill=\"${node_font}\">${node_label_xml}</text>\n")
  if (node_url)
    file(APPEND "${graph_svg}" "    </a>\n")
  endif ()
  file(APPEND "${graph_svg}" "  </g>\n")
endforeach ()

file(APPEND "${graph_svg}" "</svg>\n")

if (DEFINED GRAPHVIZ_DOT_EXECUTABLE AND GRAPHVIZ_DOT_EXECUTABLE)
  foreach(render_format png pdf)
    if (DEFINED BEXT_RENDER_${render_format} AND BEXT_RENDER_${render_format})
      execute_process(
        COMMAND "${GRAPHVIZ_DOT_EXECUTABLE}" "-T${render_format}" "-o" "${BEXT_BINARY_DIR}/bext.${render_format}" "${graph_dot}"
        COMMAND_ERROR_IS_FATAL ANY
      )
    endif ()
  endforeach ()
endif ()
